---
title: "Part 1"
author: "Bri Baker"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### `str_detect()`

```{r}
vec <- c("  A Unicorn     Fish", " add   cornmeal ", "  French FRIES", " acorn squash  ")


str_detect(vec, pattern = "corn")
```


```{r}
walk_sub <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))
```


## replace

```{r}

vec_bren <- str_replace(vec, pattern = "corn", replacement = "cool")
  

```

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

```{r}
str_trim(vec) ##leading and trailing white space

str_squish(vec) ##trim + repeated white space

```

```{r}
str_to_lower(vec)

str_to_title(vec)

str_to_sentence(vec)

```


```{r}
sw_llama <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))
```

