---
title: "Part 2"
author: "Bri Baker"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
```

```{r, cache = TRUE}
hobbit_text <- pdf_text("the-hobbit.pdf")
```

```{r}
hobbit_text_p34 <- hobbit_text[34]
```

```{r}
hobbit_tidy <- data.frame(hobbit_text) %>% 
  mutate(text_full = str_split(hobbit_text, pattern="\\r\n")) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full))
```

```{r}
hobbit_df <- hobbit_tidy %>% 
  slice(-(1:125)) %>% 
  mutate(chapter = case_when(
    str_detect(text_full, pattern = "Chapter") ~ text_full,
    TRUE ~ NA_character_
  )) %>% 
  fill(chapter) %>% 
  separate(col = chapter, into = c("ch", "no"), sep = " ") %>% 
  mutate(chapter = as.numeric(as.roman(no)))
```

```{r}
hobbit_tokens <- hobbit_df %>% 
  unnest_tokens(word, text_full) %>% 
  dplyr::select( -hobbit_text)

hobbit_wordcount <- hobbit_tokens %>% 
  count(chapter, word)
```



```{r}
hobbit_nonstop <- hobbit_tokens %>% 
  anti_join(stop_words)

nonstop_counts <- hobbit_nonstop %>% 
  count(chapter, word)
```

```{r}
top_5 <- nonstop_counts %>% 
  group_by(chapter) %>% 
  arrange(-n) %>% 
  slice(1:5)

ggplot(data = top_5, aes(x = word, y = n)) +
  geom_col(fill = "blue") +
  facet_wrap(~chapter, scales = "free") +
  coord_flip()
```

```{r}

ch1_100 <- nonstop_counts %>% 
  filter(chapter == 1) %>% 
  arrange(-n) %>% 
  slice(1:100)

ch1_cloud <- ggplot(data = ch1_100, aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n), shape = "diamond") +
  scale_size_area(max_size = 6) +
  scale_color_gradientn(colors = c("darkgreen","blue","purple")) +
  theme_minimal()

ch1_cloud
```

```{r}

afinn_pos <- get_sentiments("afinn") %>% 
  filter(value > 2)
```


```{r}
hobbit_afinn <- hobbit_nonstop %>% 
  inner_join(get_sentiments("afinn"))

afinn_counts <- hobbit_afinn %>% 
  count(chapter, value)

# Find the mean afinn score by chapter: 
afinn_means <- hobbit_afinn %>% 
  group_by(chapter) %>% 
  summarize(mean_afinn = mean(value))

```

```{r}

# Plot them: 
ggplot(data = afinn_counts, aes(x = value, y = n)) +
  geom_col() +
  facet_wrap(~chapter)



ggplot(data = afinn_means, 
       aes(x = fct_rev(as.factor(chapter)), 
           y = mean_afinn)) +
  geom_col() +
  coord_flip()
```

```{r}
hobbit_nrc <- hobbit_nonstop %>% 
  inner_join(get_sentiments("nrc"))

hobbit_nrc_counts <- hobbit_nrc %>% 
  count(chapter, sentiment)

ggplot(data = hobbit_nrc_counts, aes(x = sentiment, y = n)) +
  geom_col() +
  facet_wrap(~chapter) +
  coord_flip()
```

